-- Database Backup Created: 2025-05-30T11:19:14.454Z
-- Generated by Healthcare CRM Application

-- Error backing up table activities: column t.tablename does not exist

-- Error backing up table appointments: column t.tablename does not exist

-- Error backing up table companies: column t.tablename does not exist

-- Error backing up table contacts: column t.tablename does not exist

-- Error backing up table lead_history: column t.tablename does not exist

-- Error backing up table leads: column t.tablename does not exist

-- Error backing up table modules: column t.tablename does not exist

-- Error backing up table opportunities: column t.tablename does not exist

-- Error backing up table product_modules: column t.tablename does not exist

-- Error backing up table products: column t.tablename does not exist

-- Error backing up table quotation_items: column t.tablename does not exist

-- Error backing up table quotations: column t.tablename does not exist

-- Error backing up table sales_order_items: column t.tablename does not exist

-- Error backing up table sales_orders: column t.tablename does not exist

-- Error backing up table sales_targets: column t.tablename does not exist

-- Error backing up table session: column t.tablename does not exist

-- Error backing up table tasks: column t.tablename does not exist

-- Error backing up table teams: column t.tablename does not exist

-- Error backing up table users: column t.tablename does not exist

-- Error backing up table vendor_groups: column t.tablename does not exist

-- Error backing up table vendors: column t.tablename does not exist

