-- Database Backup Created: 2025-06-10T10:23:37.995Z
-- Generated by Healthcare CRM Application

-- Error backing up table activities: there is no parameter $1

-- Error backing up table appointments: there is no parameter $1

-- Error backing up table companies: there is no parameter $1

-- Error backing up table contacts: there is no parameter $1

-- Error backing up table lead_history: there is no parameter $1

-- Error backing up table leads: there is no parameter $1

-- Error backing up table modules: there is no parameter $1

-- Error backing up table opportunities: there is no parameter $1

-- Error backing up table product_modules: there is no parameter $1

-- Error backing up table products: there is no parameter $1

-- Error backing up table quotation_items: there is no parameter $1

-- Error backing up table quotations: there is no parameter $1

-- Error backing up table sales_order_items: there is no parameter $1

-- Error backing up table sales_orders: there is no parameter $1

-- Error backing up table sales_targets: there is no parameter $1

-- Error backing up table session: there is no parameter $1

-- Error backing up table tasks: there is no parameter $1

-- Error backing up table teams: there is no parameter $1

-- Error backing up table users: there is no parameter $1

-- Error backing up table vendor_groups: there is no parameter $1

-- Error backing up table vendors: there is no parameter $1

